language: python

dist: focal

python:
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9'

install:
  - pip install -e '.[dev]'

script:
  - black --check dikort
  - python3 -m unittest

notifications:
  slack:
    secure: oJHFicKuIxOGpc32SSMX9/GLUMJqTr+PsoeLhxFr0OokrtlGfbAPlUa5JFwvaRPnYIJ6T+zYwRsJ7m8c57EzhEMtkJv62xQsE9GkhZQr8KTpgC4yn1Kjx8e8Q5OE3/n0Ay/ovxgeusuN0yQ1+BXtGpcoet+peRb9NgCcO27u/R1hktWcGyBD2pnu/DQMo0kvDD5T9y9h//lWP7Irp+lQfa/V/JEYRBQOVtrvlvk9A4JXaegvOnOYOr1rZIK7PBcgzFOcoaxpBoWFoYhqN7/uLKhg2x4VnrtX9oYrmX23VQatiQJYB9oUrTcPbZKmA9iegzTVOal/B3MW3vnpmNotRtu3npA3LP5sXSBuNW2HM7IAChSGrfP/sw9qdZFcasp2E3Jey0AcjrfRfZmdgCTv4G2vvUIYRP8ePhfya1c2GFg1H7qM71anJPPK7VM/kb0EVVKot5nqW28jhH1/fcWYy9i8e8h4wuzkVxwPLCGCPDFdX+YF0noqNaqMvpgntLTkfUsgDKY9tejHpFumA/zNbpPujeP8BJj419a6xuWMb/jRrdFFlXhcoaThdHO81EdWuT0tMHZwL1+dDQ2Zhot4H4BQZwsqpgJV3kuYppgGiRMqFtJlXqsafr+4hvRP32pdfCuYWrjbvUcfrkLuZ53Wxe7pE4rKuAalSRmoAf8wL48=
