language: python

dist: focal

python:
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9'

install:
  - pip install -e '.[dev]'

script:
  - black --check dikort
  - python3 -m unittest

notifications:
  slack:
    secure: hekJykt179M33y5yEKxOpCDobT5RlfwsHLNekz+M4up6IBplccHr4Fxg2pnnaQA989tMNRQEeP/lKkEuiFn2bki2aG8oOlS2vxXWpbPzUBFdGNzXXuQbBjqUX8lhsG5+ccgPK9cz7G/m63aQ+sLPrsF1Jyjdnkuw15VOFg23OngHbOTdDr0Cq6p6F+eM87nqlm/tAoGqCe6J0DT8nFcHHmA3D/hqlXPnfh8ya4BfongtEOYrqvi6fcOsXZgFqVjHE6s7kbVUPBjOttb29v/MgygdDiLJCcmyHqLSXM4Z6zylgmrkacOt2yTKndsnFjvDCpfVmevZmS0kUG3LSJjPlzylz5DOMP6+fSlbW0U8B6exGIRqgYp8Y4YmS3UHyiCXXloTlAF1XcVnXLuZu+MNjkFg4TXUGyXf0BGNr+43JE6+4UAZHShcPDyDOUglk+qILZj7R4NR2WOTG9XJtPQQWREhVQeyidESFPsfYNxaCTVGLKom7bFZBsgXqmHx+nqfWn7411Ri7N/4Q7Y7IEbbO1kSe0x08lIZ+MwdgCHcfHfy/4yx6yPnI5oS+WVj6arR0Wcx4f+UwnArLPkm3q48sDV20wGCElOkoQ405jMCc+R5qHW9TZN6UUKPdp8BJW9w2hEG2fppj7zz7iAO4G7zDgRd1EwQlaHQAKd51sM7/Xo=
