[tool.black]
line-length=120

[tool.isort]
force_grid_wrap=0
use_parentheses=true
ensure_newline_before_comments=true
line_length=80
include_trailing_comma=true
multi_line_output=3
default_section='THIRDPARTY'

